spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/company/api/order/**, /assets/**, /favicon.ico
          filters:
            - RewritePath=/company(?<segment>/?.*), $\{segment}
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/company/api/payment/**
          filters:
            - RewritePath=/company(?<segment>/?.*), $\{segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.gateway: TRACE